### ISSUE TITLE
Join translation id_ID

### ISSUE THREAD

**Issue by anaufalm** [Human-Phenotype-Ontology/HPO-translations#4]
Hi, I'm Indonesian translator, I want to translate this project into Indonesian language. Thank you for attention. Cheers!

**Comment by iamkoehler** [comment]
Translations are managed here: https://crowdin.com/project/hpo-translation

We currently do not have Indonesian as target language.

**Comment by anaufalm** [comment]
Can you add Indonesian string there? I also Crowdin translator [@anaufalm](https://crowdin.com/profile/anaufalm). I can help translate your project into Indonesian if possible.
